#ifndef EVENT_TRIGGER_MSG_INCLUDE
#define EVENT_TRIGGER_MSG_INCLUDE 1

const int EVENT_TRIGGER_MSG_TYPE_REQUEST = 0;
const int EVENT_TRIGGER_MSG_TYPE_RESPONSE = 1;

const int EVENT_TRIGGER_EVENT_TYPE_VISITOR = 0;
const int EVENT_TRIGGER_EVENT_TYPE_ASSISTANT = 1;

const int EVENT_TRIGGER_RESULT_FAILURE = 0;
const int EVENT_TRIGGER_RESULT_SUCCESS = 1;

#endif EVENT_TRIGGER_MSG_INCLUDE