#ifndef PERFORM_TASK_SRV_INCLUDE
#define PERFORM_TASK_SRV_INCLUDE 1

// PerformTask.srv
const int PERFORM_TASK_RESULT_ACCEPTED = 0;
const int PERFORM_TASK_RESULT_FINISHED = 1;
const int PERFORM_TASK_RESULT_BUSY = 2;

const int TASK_PROGRESS_THRESHOLD = 50;

#endif
