define letter-G model
(
  size [3 0.5 3]
  obstacle_return 0
  gui_move 1
  block
  (
    color "black"
    points [4]
    point[0] [0 0]
    point[1] [0 1]
    point[2] [7 1]
    point[3] [7 0]
    z [0 1]
  )
  block
  (
    color "black"
    points [4]
    point[0] [0 0]
    point[1] [0 1]
    point[2] [1 1]
    point[3] [1 0]
    z [1 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [6 0]
    point[1] [6 1]
    point[2] [7 1]
    point[3] [7 0]
    z [1 4]
  )
  block
  (
    color "black"
    points [4]
    point[0] [3 0]
    point[1] [3 1]
    point[2] [6 1]
    point[3] [6 0]
    z [3 4]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [7 1]
    point[3] [7 0]
    z [6 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [6 0]
    point[1] [6 1]
    point[2] [7 1]
    point[3] [7 0]
    z [5 6]
  )
)

define letter-R model
(
  size [3 0.5 3]
  obstacle_return 0
  gui_move 1
  block
  (
    color "black"
    points [4]
    point[0] [0 0]
    point[1] [0 1]
    point[2] [1 1]
    point[3] [1 0]
    z [0 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [6 0]
    point[1] [6 1]
    point[2] [7 1]
    point[3] [7 0]
    z [0 3]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [6 1]
    point[3] [6 0]
    z [3 4]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [7 1]
    point[3] [7 0]
    z [6 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [6 0]
    point[1] [6 1]
    point[2] [7 1]
    point[3] [7 0]
    z [4 6]
  )
)

define letter-O model
(
  size [3 0.5 3]
  obstacle_return 0
  gui_move 1
  block
  (
    color "black"
    points [4]
    point[0] [0 0]
    point[1] [0 1]
    point[2] [1 1]
    point[3] [1 0]
    z [0 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [6 0]
    point[1] [6 1]
    point[2] [7 1]
    point[3] [7 0]
    z [0 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [6 1]
    point[3] [6 0]
    z [6 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [6 1]
    point[3] [6 0]
    z [0 1]
  )
)

define letter-U model
(
  size [3 0.5 3]
  obstacle_return 0
  gui_move 1
  block
  (
    color "black"
    points [4]
    point[0] [0 0]
    point[1] [0 1]
    point[2] [1 1]
    point[3] [1 0]
    z [0 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [6 0]
    point[1] [6 1]
    point[2] [7 1]
    point[3] [7 0]
    z [0 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [6 1]
    point[3] [6 0]
    z [0 1]
  )
)

define letter-P model
(
  size [3 0.5 3]
  obstacle_return 0
  gui_move 1
  block
  (
    color "black"
    points [4]
    point[0] [0 0]
    point[1] [0 1]
    point[2] [1 1]
    point[3] [1 0]
    z [0 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [6 0]
    point[1] [6 1]
    point[2] [7 1]
    point[3] [7 0]
    z [3 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [6 1]
    point[3] [6 0]
    z [3 4]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [6 1]
    point[3] [6 0]
    z [6 7]
  )
)

define letter-N model
(
  size [3 0.5 3]
  obstacle_return 0
  gui_move 1
  block
  (
    color "black"
    points [4]
    point[0] [0 0]
    point[1] [0 1]
    point[2] [1 1]
    point[3] [1 0]
    z [0 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [6 0]
    point[1] [6 1]
    point[2] [7 1]
    point[3] [7 0]
    z [0 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [6 1]
    point[3] [6 0]
    z [6 7]
  )
)

define letter-E model
(
  size [3 0.5 3]
  obstacle_return 0
  gui_move 1
  block
  (
    color "black"
    points [4]
    point[0] [0 0]
    point[1] [0 1]
    point[2] [1 1]
    point[3] [1 0]
    z [0 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [6 1]
    point[3] [6 0]
    z [3 4]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [7 1]
    point[3] [7 0]
    z [6 7]
  )
  block
  (
    color "black"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [7 1]
    point[3] [7 0]
    z [0 1]
  )
)
