define nurseRobot position
(
  size [0.75 0.75 0.75]
  drive "diff"
  obstacle_return 0
  block
  (
    color "pink"
    points [4]
    point[0] [0 0]
    point[1] [0 1]
    point[2] [1 1]
    point[3] [1 0]
    z [0 1.5]
  )
  block
  (
    color "white"
    points [4]
    point[0] [0 1]
    point[1] [0 2]
    point[2] [1 2]
    point[3] [1 1]
    z [0 1.5]
  )
  block
  (
    color "pink"
    points [4]
    point[0] [1 1]
    point[1] [1 2]
    point[2] [2 2]
    point[3] [2 1]
    z [0 1.5]
  )
  block
  (
    color "white"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [2 1]
    point[3] [2 0]
    z [0 1.5]
  )
  block
  (
    color "white"
    points [4]
    point[0] [0 0]
    point[1] [0 1]
    point[2] [1 1]
    point[3] [1 0]
    z [1.5 3]
  )
  block
  (
    color "pink"
    points [4]
    point[0] [0 1]
    point[1] [0 2]
    point[2] [1 2]
    point[3] [1 1]
    z [1.5 3]
  )
  block
  (
    color "white"
    points [4]
    point[0] [1 1]
    point[1] [1 2]
    point[2] [2 2]
    point[3] [2 1]
    z [1.5 3]
  )
  block
  (
    color "pink"
    points [4]
    point[0] [1 0]
    point[1] [1 1]
    point[2] [2 1]
    point[3] [2 0]
    z [1.5 3]
  )
)
