define resident position
(
  size [1.5 1.5 3]
  drive "diff"
  obstacle_return 0
  block
  (
    color "brown"
    points [4]
    point[0] [0 1]
    point[1] [0 2]
    point[2] [.65 2]
    point[3] [.65 1]
    z [0 0.2]
  )
  block
  (
    color "brown"
    points [4]
    point[0] [0 2]
    point[1] [0 3]
    point[2] [.65 3]
    point[3] [.65 2]
    z [0 0.2]
  )
  block
  (
    color "green"
    points [4]
    point[0] [0 1]
    point[1] [0 2]
    point[2] [.5 2]
    point[3] [.5 1]
    z [0.2 1.1]
  )
  block
  (
    color "green"
    points [4]
    point[0] [0 2]
    point[1] [0 3]
    point[2] [0.5 3]
    point[3] [0.5 2]
    z [0.2 1.1]
  )
  block
  (
    color "white"
    points [4]
    point[0] [0 1]
    point[1] [0 3]
    point[2] [.5 3]
    point[3] [.5 1]
    z [1.1 1.7]
  )
  block
  (
    color "white"
    points [4]
    point[0] [0 0]
    point[1] [0 4]
    point[2] [0.5 4]
    point[3] [0.5 0]
    z [1.7 2]
  )
  block
  (
    color "pink"
    points [4]
    point[0] [0 0]
    point[1] [0 1]
    point[2] [0.5 1]
    point[3] [0.5 0]
    z [1.1 1.7]
  )
  block
  (
    color "pink"
    points [4]
    point[0] [0 3]
    point[1] [0 4]
    point[2] [0.5 4]
    point[3] [0.5 3]
    z [1.1 1.7]
  )
  block
  (
    color "pink"
    points [4]
    point[0] [-0.1 0.5]
    point[1] [-0.1 3.5]
    point[2] [.6 3.5]
    point[3] [.6 0.5]
    z [2 2.8]
  )
  block
  (
    color "brown"
    points [4]
    point[0] [-0.1 0.5]
    point[1] [-0.1 3.5]
    point[2] [.6 3.5]
    point[3] [.6 0.5]
    z [2.8 3]
  )
)
